name: Chequeamos warnings

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v3

      - name: Configuración del JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Descarga del Checkstyle para chequear warnings del código
        run: |
          wget -q -O checkstyle.jar \
            https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.13.0/checkstyle-10.13.0-all.jar

      - name: Creación de una configuración mínima del Checkstyle
        run: |
          cat << 'EOF' > checkstyle.xml
          <?xml version="1.0"?>
          <!DOCTYPE module PUBLIC
              "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
              "https://checkstyle.org/dtds/configuration_1_3.dtd">
          <module name="Checker">
            <module name="TreeWalker">
              <!-- Detect unused imports -->
              <module name="UnusedImports"/>
              <!-- Detect unused local variables -->
              <module name="UnusedLocalVariable"/>
            </module>
          </module>
          EOF

      - name: Correr Checkstyle en el src
        run: |
          java -jar checkstyle.jar \
            -c checkstyle.xml \
            src/main/java
      
      - name: Correr Checkstyle en los tests
        run: |
          java -jar checkstyle.jar \
            -c checkstyle.xml \
            test/main/java