name: Chequear warnings del proyecto
on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v3

      - name: Configuración del JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Descargamos Checkstyle para verificar los warnings
        run: |
          wget -q -O checkstyle.jar \
            https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.13.0/checkstyle-10.13.0-all.jar
          wget -q -O google_checks.xml \
            https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

      - name: Corremos Checkstyle
        run: |
          java -jar checkstyle.jar \
            -c google_checks.xml \
            src/main/java src/test/java